### ISSUE TITLE
feat: prevent secrets from leaking to source control

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/monorepo#156]
**Is your feature request related to a problem? Please describe.**

Follow up of 
https://github.com/verdaccio/ui/pull/139
https://github.com/verdaccio/verdaccio/pull/1373
https://github.com/verdaccio/verdaccio/pull/1408

**Describe the solution you'd like**

enable: **feat: prevent secrets from leaking to source control**

**Comment by joshghent** [comment]
@juanpicado - I'll try to knock this out today!
