### ISSUE TITLE
Add @verdaccio/babel-preset

### ISSUE THREAD

**Issue by sergiohgz** [verdaccio/monorepo#2]
Create a package that contains a common Babel config for every Verdaccio project.

The syntax to include this _preset_ in `.babelrc` files is:
```json
{
  "presets": ["@verdaccio"]
}
```

We should allow users to customize the _preset_ settings by enabling and disabling with some `options`. One example is activating React _preset_ (for React projects) with:
```json
{
  "presets": [
    ["@verdaccio", { "enableReact": true }]
  ]
}
``` 

One thing I want to discuss is if the _package_ should be __self-contained__. This means that every project that install it will not need to install any Babel dependency (as this will include every preset but can be enabled or disabled with _options_ object).

**Comment by juanpicado** [comment]
Babel 7 is out
https://twitter.com/github/status/1034867850052157440

**Comment by sergiohgz** [comment]
I close this issue because we have this [Babel Preset](https://github.com/verdaccio/babel-preset) we will migrate here
