### ISSUE TITLE
`require.requireActual` is deprecated

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/monorepo#213]
**Is your feature request related to a problem? Please describe.**

```
require.requireActual('babel/polyfill');
```

Is deprecated

**Describe the solution you'd like**
Find a new API that solve this.

**Describe alternatives you've considered**

No alternative yet.

**Additional context**

<img width="377" alt="Screen Shot 2019-10-19 at 10 16 14 AM" src="https://user-images.githubusercontent.com/558752/67140299-8a6e3400-f259-11e9-98a7-88e257b8a4f9.png">

**Comment by abc516** [comment]
Hi @juanpicado , I'd like to tackle this. any tips on how to proceed?

**Comment by juanpicado** [comment]
@abc516  According the code at `jest` says 

```
interface NodeRequire {
    /**
     * Returns the actual module instead of a mock, bypassing all checks on
     * whether the module should receive a mock implementation or not.
     *
     * @deprecated Use `jest.requireActual` instead.
     */
    requireActual(moduleName: string): any;
    /**
     * Returns a mock module instead of the actual module, bypassing all checks
     * on whether the module should be required normally or not.
     *
     * @deprecated Use `jest.requireMock`instead.
     */
    requireMock(moduleName: string): any;
}
```
I think just replace nanes, that would be all.

**Comment by DanielRuf** [comment]
Hey @abc516,

many thanks for taking care of that.
I guess we can close this issue then?
