### ISSUE TITLE
Add core packages

### ISSUE THREAD

**Issue by sergiohgz** [verdaccio/monorepo#23]
From #13, I would like to separate in different tasks the import of packages. I think the best separation is by the type of packages.

The purpose of this issue is track the import of core packages, composed by:

- [x] @verdaccio/types from [verdaccio/flow-types](https://github.com/verdaccio/flow-types)
- [x] @verdaccio/file-locking from [verdaccio/file-locking](https://github.com/verdaccio/file-locking)
- [x] @verdaccio/streams from [verdaccio/streams](https://github.com/verdaccio/streams)
- [x] @verdaccio/readme from [verdaccio/readme](https://github.com/verdaccio/readme)
- [x] @verdaccio/commons-api from [verdaccio/commons-api](https://github.com/verdaccio/commons-api)

**Comment by juanpicado** [comment]
https://github.com/verdaccio/commons-api

**Comment by sergiohgz** [comment]
@juanpicado we need to move issues from others repositories here, like [this issue](https://github.com/verdaccio/streams/issues/36), to don't forget there :wink:

**Comment by juanpicado** [comment]
Sure, I archived those do not have any ticket.
