### ISSUE TITLE
Add plugin packages

### ISSUE THREAD

**Issue by sergiohgz** [verdaccio/monorepo#24]
From #13, I would like to separate in different tasks the import of packages. I think the best separation is by the type of packages.

The purpose of this issue is track the import of plugin packages, composed by:

- [x]  @verdaccio/local-storage from [@verdaccio/local-storage](https://github.com/verdaccio/local-storage)
- [x] verdaccio-htpasswd from [verdaccio-htpasswd](https://github.com/verdaccio/verdaccio-htpasswd)
- [x]  verdaccio-google-cloud from [verdaccio-google-cloud](https://github.com/verdaccio/verdaccio-google-cloud)
- [x] verdaccio-aws-s3-storage from [verdaccio-aws-s3-storage](https://github.com/verdaccio/verdaccio-aws-s3-storage)
- [x] verdaccio-memory from [verdaccio-memory](https://github.com/verdaccio/verdaccio-memory)
- [x] verdaccio-audit from [verdaccio-audit](https://github.com/verdaccio/verdaccio-audit)
- [x] verdaccio-auth-memory from [verdaccio-auth-memory](https://github.com/verdaccio/verdaccio-auth-memory)
- [x] verdaccio-activedirectory from https://github.com/verdaccio/verdaccio-activedirectory

**Comment by juanpicado** [comment]
From this list, I'd suggest skip, Google and Local Storage, aside of that, all are candidates for migration.

**Comment by griffithtp** [comment]
will continue with the above list once htpasswd is merge and use as an inspiration ✨

**Comment by sergiohgz** [comment]
Take a look at discord, as you are the master of plugins importation :wink:

**Comment by sergiohgz** [comment]
@griffithtp @juanpicado I'm going to start with _verdaccio-memory_ import

**Comment by juanpicado** [comment]
I will take care of the Google Plugin.

**Comment by sergiohgz** [comment]
I've just migrated verdaccio-auth-memory plugin, and I want to continue with verdaccio-audit if you doesn't mind @juanpicado @griffithtp

**Comment by juanpicado** [comment]
@sergiohgz @griffithtp google cloud plugin is ready for migration, I already merged all of it.

**Comment by griffithtp** [comment]
> @sergiohgz @griffithtp google cloud plugin is ready for migration, I already merged all of it.

I will get cracking on aws and gcp :)

**Comment by juanpicado** [comment]
Local storage is almost ready, we just need to finish https://github.com/verdaccio/local-storage/pull/168 and we can move it here.

**Comment by juanpicado** [comment]
@griffithtp @sergiohgz  https://github.com/verdaccio/local-storage can be moved already.

**Comment by juanpicado** [comment]
Candidates to migrate https://github.com/verdaccio/verdaccio-activedirectory this to babel, eslint etc etc ? @verdaccio/collaborators and then move it here?

**Comment by sergiohgz** [comment]
@juanpicado We can migrate activedirectory here and then refactor with new tools (ts, babel, eslint, etc).

I'm going to start with local-storage :smiley:

**Comment by juanpicado** [comment]
`verdaccio-activedirectory` is ready for migration 👍

**Comment by sergiohgz** [comment]
@juanpicado great, I will start right now to have it before go to sleep :stuck_out_tongue_winking_eye:

**Comment by sergiohgz** [comment]
All the plugins are imported, so I'm going to close this issue

**Comment by juanpicado** [comment]
Wow !! This process was fast 🚀🚀🚀🚀
