### ISSUE TITLE
Refactor CI

### ISSUE THREAD

**Issue by sergiohgz** [verdaccio/monorepo#254]
**Describe the bug**
When external PRs triggers CircleCI run, the workflow fails trying to publish canary packages in our Verdaccio instance, because it tries to get the secret key for publishing. I want to migrate that part of the workflow to Github Actions and create a message in the PR with the canary version published.

**Comment by favoyang** [comment]
+1 the bug breaks my PR.

**Comment by sergiohgz** [comment]
I'm in that, but it not easy to migrate to an ellegant solution. Stay tuned :wink:

**Comment by sergiohgz** [comment]
Right now, on master branch have been disable canary releases. I think I have time this week to complete.

**Comment by juanpicado** [comment]
Closing this, packages are moving away anyway.
