### ISSUE TITLE
@verdaccio/eslint-config@8.4.1 and @verdaccio/babel-preset@8.4.1 do not exist

### ISSUE THREAD

**Issue by favoyang** [verdaccio/monorepo#272]
**Describe the bug**
https://github.com/verdaccio/monorepo/commit/8d7ca5bb31fff96281a0896c72f9f1426fa8b728, the 8.4.1 release breaks plugins/aws-s3-storage, and perhaps other, due to `@verdaccio/eslint-config@8.4.1` and `@verdaccio/babel-preset@8.4.1` do not exist.

**To Reproduce**
1. Checkoust monorepo
2. Go to plugins/aws-s3-storage
2. `npm install`

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @verdaccio/babel-preset@^8.4.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'aws-s3-storage'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/verdaccio/.npm/_logs/2019-11-23T14_42_18_694Z-debug.log
```

**Comment by sergiohgz** [comment]
Correct, due to the incident occurred yesterday to npmjs (you can see at the release notes), we cannot complete publish process. Versions 8.4.0 and 8.4.1 are affected. I'm going to publish 8.4.2 fixing the problem

**Comment by sergiohgz** [comment]
Try again, 8.4.2 have been published satisfactory. If the problem still happens, please, reopen the issue. Thanks @favoyang

**Comment by juanpicado** [comment]
It works fine in UI
