### ISSUE TITLE
Add @babel/plugin-syntax-top-level-await

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/monorepo#273]
**Is your feature request related to a problem? Please describe.**

I'd love to have `@babel/plugin-syntax-top-level-await` to be used

https://babeljs.io/blog/2019/11/05/7.7.0

```
parser.parse(inputCode, {
  plugins: ["topLevelAwait"]
});
```

**Comment by DanielRuf** [comment]
So we need a PR here?

**Comment by juanpicado** [comment]
yes 👍

**Comment by sergiohgz** [comment]
I think we cannot achieve this already. Babel doesn't transform top level await, as said in package documentation: https://babeljs.io/docs/en/babel-plugin-syntax-top-level-await

**Comment by DanielRuf** [comment]
> webpack@5's experiments.topLevelAwait options.

Let's try this.

**Comment by sergiohgz** [comment]
The problem is that the most number of projects in Verdaccio monorepo are not bundlelized using Webpack, are transpiled with Babel, so I think this could be applied to Verdaccio main project and ui directly, but not for the rest right now.

**Comment by juanpicado** [comment]
This comes out of the box with Typescript
