### ISSUE TITLE
Add support for optional-chaining and nullish-coalescing-operator

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/monorepo#274]
**Is your feature request related to a problem? Please describe.**

optional-chaining and nullish-coalescing-operator do not come by default, we need include dependencies in `babel-preset`. 

https://github.com/babel/babel/tree/master/packages/babel-plugin-proposal-optional-chaining
https://github.com/babel/babel/tree/master/packages/babel-plugin-proposal-nullish-coalescing-operator

**Comment by anikethsaha** [comment]
in `ui` alone or in others too?
is these two being used in the main repo too?

**Comment by juanpicado** [comment]
Main repo until I finish the yarn migration, here feel free :)

**Comment by anikethsaha** [comment]
Yeo....I will try to update it here by next week

**Comment by sergiohgz** [comment]
@anikethsaha let me try, there are several dependencies to update, including `@typescript-eslint`. I'm going to create a PR sooner :wink:
