### ISSUE TITLE
seperate s3 subfolders (key prefix for different packages)

### ISSUE THREAD

**Issue by tetrohed** [verdaccio/monorepo#298]
**Is your feature request related to a problem?**
 Currently, the s3 plugin adds all packages (proxy or none proxy) flat out in the root of s3 bucket.
**Describe the solution you'd like**
Ideally, the storage: custom_folder for every package regex should also work for the s3.

```packages:
'@*/*':
access: $all
publish: $all
proxy: npmjs
storage: custom_folder
```

this would cache the packages to s3/bucket/custom_folder

**Rationale** 
 we want to have our private packages persistently in S3, and cache npmjs packages there as well. But be able to clear the whole cache at regular intervals without touching our own private packages. Having these two separated makes maintenance easier.

**Alternatives**
For now we have been setting cache:false for npmjs uplinks to avoid polluting our s3 instance

**Additional context**
I would be able to make a PR on this, but I have a couple of questions in this regard:
 - Do plugins get instantiated per package section? if thats the case the key prefix in aws-s3-storage can be utilized to achieve the goal
 - currently, when we are setting the store to aws-s3-storage, local storage seems to be automatically turned off. How does this happen architecturally? Is s3-plugin turning the local storage off? Or is this simply a bug?

**Comment by tetrohed** [comment]
hey @juanpicado thanks for the update! if you give me a couple of pointers on my questions, I can grab this.

**Comment by favoyang** [comment]
The s3 path is defined in [s3PackageManager.ts](https://github.com/verdaccio/monorepo/blob/master/plugins/aws-s3-storage/src/s3PackageManager.ts), but I wonder how to get the proxy information there (whether a package is local or proxy).

Logically only one storage active at a time.

**Comment by juanpicado** [comment]
The storage plugin can access to the config app properties, thus the package access section. You can see the `local-storage` implementation and here is how is done.

![monorepo____projects__verdaccio_monorepo__-_____plugins_local-storage_src_local-database_ts__monorepo_](https://user-images.githubusercontent.com/558752/71463513-e94ead00-27b6-11ea-9bfe-e429af3f3752.png)

@favoyang 
> but I wonder how to get the proxy information there (whether a package is local or proxy).

Storage Plugin should not be aware of the source of the package, his job is just store stuff. Why that would be related with the question of this ticket? 🤔

**Comment by favoyang** [comment]
I thought @tetrohed wants to know if a package is local or upstream cached, so to give different storage path prefix. i.e. store all private packages to `private/` and cached packages to `upstream/`. For his specific management purpose. To achieve this storage plugin has to know the source of a package,  if it is cached or not, right?

I also wonder the intention to clear cache.

**Comment by tetrohed** [comment]
hey guys, a bit of information as to intent, maybe it was misleading to talk about clearing the cache. Our Purpose is actually is an easier of book keeping, mainly because the structure of config file is reflected on s3 as opposed to node_modules structure.

> Logically only one storage active at a time.

right, but s3 has precedence to local_storage?

@juanpicado also I think you are right about the source of package being irrelevant.

@favoyang custom folder with names private/ or upstream/ can be easily done in config.ts as follows:

    '@private/*':
    access: $authenticated
    publish: $authenticated
    storage: private
    '@*/*':
    access: $all
    publish: $all
    proxy: npmjs
    storage: upstream

**Comment by tetrohed** [comment]
ah I had another issue, with where the call for packageManager was, but found it in 

https://github.com/verdaccio/monorepo/blob/e269378a704559a3bd4a655cddb9d8b0e614d752/plugins/aws-s3-storage/src/index.ts#L176

Makes sense now, I ill take a crack at this after hollidays ;) not at my station currenlty

**Comment by tetrohed** [comment]
hey @juanpicado all tests that I see in the plugin are skipped, is this expected?

https://github.com/verdaccio/monorepo/blob/21c47d3360699577961e35d6720cb126f7011036/plugins/aws-s3-storage/tests/s3PackageManager.test.ts#L18

**Comment by juanpicado** [comment]
@tetrohed test were flaky ... still a lot of work to do there, that's the reason why are skipped. Original tests were running against AWS, which make them more E2E than unit test.

**Comment by tetrohed** [comment]
ah ok I try to write some against mocks then

**Comment by tetrohed** [comment]
@juanpicado another quick question, how do you guys test everything locally? I don't seem to find any orchestration (docker-compose or otherwise)

**Comment by juanpicado** [comment]
My unique way to test is using Localstack https://github.com/verdaccio/docker-examples/tree/master/amazon-s3-docker-example/v4

**Comment by favoyang** [comment]
I tested with https://min.io/ locally, but I'm not sure if that is suitable for the CI.

**Comment by tetrohed** [comment]
for the ci I have written tests, I just wanted to test everything locally before PR.

**Comment by favoyang** [comment]
See this then, https://github.com/verdaccio/monorepo/pull/289#issuecomment-567495724

**Comment by juanpicado** [comment]
It would be great to have a minio example at docker repo, would be really useful for mentoring.  @favoyang 👏

**Comment by tetrohed** [comment]
the part with minio is actually quiet clear. I cannot figure out where to place the plugin itself

**Comment by juanpicado** [comment]
I will explain here how it works soon detailed
