### ISSUE TITLE
Upgrade dependencies from several packages

### ISSUE THREAD

**Issue by sergiohgz** [verdaccio/monorepo#309]
There are some upgrades blocked due to our time. I want to share a table with the package, dependency to upgrade and, the current and target version.

| Package                  | Dependency              | Current | Target | 
|--------------------------|-------------------------|---------|--------|
| @verdaccio/readme        | marked                  | 0.7.0   | 0.8.0  |
| verdaccio-aws-s3-storage | @verdaccio/commons-api  | 0.1.2   | 8.5.0  |
| verdaccio-aws-s3-storage | @verdaccio/streams      | 2.0.0   | 8.5.2  |
| verdaccio-google-cloud   | @google-cloud/datastore | 4.5.0   | 5.0.2  |
| verdaccio-google-cloud   | @google-cloud/storage   | 3.5.0   | 4.1.3  |
| verdaccio-google-cloud   | fast-crc32c             | 1.0.4   | 2.0.0  |
| verdaccio-htpasswd       | @verdaccio/file-locking | 1.0.0   | 8.5.2  |
| @verdaccio/local-storage | level                   | 5.0.1   | 6.0.0  |

I'm going to close the current PRs opened by @dependabot, but I will mention this issue to follow up.

Also, I'm investigating some of them to make this upgrade faster :wink:

**Comment by agar23** [comment]
@sergiohgz need any help with this guy? happy to pick anything up 😄

**Comment by juanpicado** [comment]
I would ignore AWS and Google Cloud Related until we make test run, otherwise we cannot so regression

**Comment by juanpicado** [comment]
Due #387
