### ISSUE TITLE
(aws-s3-storage) Support for environment variables

### ISSUE THREAD

**Issue by nszilard** [verdaccio/monorepo#314]
**Is your feature request related to a problem? Please describe.**
I'm using Verdaccio with the `verdaccio-aws-s3-storage` plugin in a dockerized setup (ECS Fargate). Since the `bucket`, `key-prefix` and `region` attributes don't support environment variables, I cannot deploy the same image in different environments.

**Describe the solution you'd like**
The solution could be simple as trying assume that the value corresponds to an environment variable, read that variable and use it as the value. If the environment is not set (empty) then fall back to current behaviour and just use the value as it is.
This behaviour would mimic how other Verdaccio plugins behave (e.g.: `verdaccio-github-oauth-ui`)

**Describe alternatives you've considered**
The alternative solution could be publishing `-dev` suffixed Docker images.

**Additional context**

**Comment by juanpicado** [comment]
I like this, I had the same issue with the google plugin, it is doable.

**Comment by nszilard** [comment]
I have started working on this, but not sure about the test as they are being skipped as far as I understood.

**Comment by juanpicado** [comment]
We just enabled some, partly are disabled. Hopefully enough, I am not sure how to mock env variables but if you find the way would be cool update the new ones.

**Comment by nszilard** [comment]
I gave a shot at writing some tests (fair warning: I'm not familiar with typescript at all 😂 ), though not sure if they are acceptable. My idea was to pull out the environment checking into a function, and then it could be tested as a "black box".

Please let me know your thoughts!

**Comment by juanpicado** [comment]
all good @nszilard
