### ISSUE TITLE
Google Cloud plugin status

### ISSUE THREAD

**Issue by Phuurl** [verdaccio/monorepo#337]
The Google Cloud plugin has the following message on the Readme:

> ⚠️⚠️ This plugin is experimental and might be unstable. It requires further testing. ⚠️⚠️

Is it known what further testing is required / how finished this plugin is?

Thanks

**Comment by juanpicado** [comment]
Hi @Phuurl 

That message means we need feedback. I created the plugin but actually I don't use it. There are few downloads every week but we have not much feedback

https://www.npmjs.com/package/verdaccio-google-cloud

I've heard people using it but that's pretty much all. There is no easy way to run tests in locally with a real google cloud environment as far as I know.
