### ISSUE TITLE
Backup htpasswd on s3

### ISSUE THREAD

**Issue by himanshumehta1114** [verdaccio/monorepo#358]
**Is your feature request related to a problem?**
I am using `verdaccio-aws-s3-storage` plugin to store my packages. So I see all my packages and `verdaccio-db.json` file on s3 but the `htpasswd` is present on my local. So when I attach my s3 bucket to other instance as my rescue plan if the instance goes down. Then user will have to create the account again. Which shouldn't be the case. So do we have any way to store my `htpasswd` file as well on s3.

**Describe the solution you'd like**
Update `htpasswd` file on s3 as well when new user is added.

**Comment by juanpicado** [comment]
This plugin does not scale well due the `.verdaccio-db.json`. It is by design. The `verdaccio-db.json` contains a secret key which is used as salt for sign the passwords, if your other instance has `verdaccio-db.json` with a different token, then users need to be created again even if the `htpasswd` is the same.  Just keep the secret key and `htpasswd` on sync

**Comment by pusherman** [comment]
I also needed a persistent way to store users for running Verdaccio in AWS EKS Fargate (since EFS volumes are not supported at the moment).  I decided to write an auth plugin for storing users in a DynamoDB table.  Disclaimer: It is very new :)

https://www.npmjs.com/package/verdaccio-dynamodb

**Comment by star-scream-7** [comment]
Hi @juanpicado 

I'm using verdaccio-s3-storage for accessing package and I have htpasswd file with an user in s3 bucket.

I'm trying to configure htpasswd file from s3 bucket like below in config.yaml file:

store:
  aws-s3-storage:
    bucket: bucket-name
    #keyPrefix: some-prefix # optional, has the effect of nesting all files in >
    region: region # optional, will use aws s3's default behavior if not sp>
    accessKeyId: A********************* # optional, aws accessKeyId for private S>
    secretAccessKey: h********************  # optional, aws >
    auth:
      htpasswd:
        file: ./htpasswd


But, when I create an user, its getting added in local htpasswd file or try to login as the user in htpasswd, I'm not able to login.

Kindly advise how to access htpasswd file in local from s3 bucket and write new user into it.

**Comment by juanpicado** [comment]
@pusherman awesome I'd add it to the website for bigger visibility.

@himanshumehta1114 I'd rather ask in the chat or create a StackOverflow question, you reach a bigger audience. `htpasswd` and this plugin are two different things. You would need to share more info to get a more accurate answer.

I'll close this one, seems I already answered and I got no response.

**Comment by himanshumehta1114** [comment]
@juanpicado Thanks for the reply. 
I get it. Packages and Auth are two separate things. So I'll have to manage them separately.

**Comment by juanpicado** [comment]
@himanshumehta1114 oppss I tagged the wrong person, my answer for you was above https://github.com/verdaccio/monorepo/issues/358#issuecomment-623849573 

:) sorry the confusion.
