### ISSUE TITLE
Refactor CONTRIBUTING

### ISSUE THREAD

**Issue by sergiohgz** [verdaccio/monorepo#36]
We need to explain better how to contribute to the project, a good guidelines about which commands contributors will need and the purpose, how to work with Lerna and packages (alltogether or separately), how to create and add new packages, how to flat devDependencies and how we manage dependencies. 

Also, we think this project is a good point to start trying the new VSCode feature called [Remote Development](https://code.visualstudio.com/docs/remote/remote-overview) to give new contributors a environment with some great settings and plugins they would need to develop, but this will be done before and improved in next iterations with more features

Things to do:
- [x] Refactor Contributor guide
- [x] Explain Lerna + Yarn Workspaces and how we use them
- [x] Explain useful Lerna commands
- [x] Explain how to work with packages alltogether (example, how to run tests or lint before pushing to git)
- [x] Explain how to work with packages in their simple unit (example, how to run compiler to see if my new feature in package x compiles)
- [x] Explain how to create packages
- [x] Explain how to import packages
- [x] Explain how we manage dependencies, devDependencies and how to flatten devDeps
- [x] _(Optionally)_ Explain how to work with VSCode Remote Development

**Comment by juanpicado** [comment]
I am quite interested in the latest one 🙃

**Comment by sergiohgz** [comment]
I marked as completed everything that is done in #51. If something have been forgotten, remember it and I'll add ASAP

**Comment by sergiohgz** [comment]
Closed via #51
