### ISSUE TITLE
Create storage plugin for Firebase Storage

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/monorepo#39]
https://firebase.google.com/docs/storage/web/start

Example:

https://github.com/verdaccio/verdaccio-memory
https://github.com/verdaccio/local-storage

**Comment by anikethsaha** [comment]
I think Firebase's storage is GCP's storage. 
It uses the GCP's storage bucket. So I guess it won't make much sense to make this plugin as those keys will be same as GCP's keys.
