### ISSUE TITLE
New Feature for aws-s3-plugin

### ISSUE THREAD

**Issue by nirwanrajnp** [verdaccio/monorepo#412]
**Is your feature request related to a problem? Please describe.**
Right now, due to some limitation if you are using aws-s3-storage plugin you can't publish a package greater than 100mb. 
I have package that is about 250mb and I always end up getting socket hang up when I use the s3-plugin. When I was not using the plugin, I was able to publish this particular package by changing max-body-size in config but I guess this config does not apply when I am using the aws-s3-plugin.

**Describe the solution you'd like**
If an option like max-body-size could be given in aws-s3-plugin config it would be pretty good.

**Describe alternatives you've considered**
I tried using verdaccio-memory plugpin but I guess that does not work with aws-s3-plugin. I could not find anything else to remedy the issue.

**Comment by juanpicado** [comment]
Please create a discussion here https://github.com/verdaccio/monorepo/issues/412 (IDEA) to open a discussion
