### ISSUE TITLE
types - forced namespace 

### ISSUE THREAD

**Issue by sosoba** [verdaccio/monorepo#413]
The `types` documentation proposes to import definitions from scoped package  `@verdaccio/types` which are other than convention.

```ts
import type {ILocalData, LocalStorage, Logger, Config} from '@verdaccio/types';
// instead of 
import type {ILocalData, LocalStorage, Logger, Config} from 'verdaccio';
```
I understand that this is due to the desire to avoid publication by DefinitelyTyped.

Since `npm 6` there is another solution - package aliasing. Simply:
`npm i -D @types/verdaccio@npm:@verdaccio/types@latest`
which download `@verdaccio/types` and install it as `@types/verdaccio`.

Unfortunately, this solution won't work because the definition file has hard-coded declared namespace:
```ts
declare module '@verdaccio/types' {
  // declarations
}
```
which, in fact, is not necessarily - Typescript will take it from package name. 

I submit a proposal to remove this wrapper and add to the documentation an alternative installation method.

**Comment by juanpicado** [comment]
hi @sosoba 

The code on this repo is basically deprecated. Now all lives here in a big monorepo 

https://github.com/verdaccio/verdaccio/tree/master/packages/types

If you have a new proposal feel free to drop it, check the current status, and let me know what we can improve.
