### ISSUE TITLE
audit-plugin: `node-fetch` should be updated

### ISSUE THREAD

**Issue by viceice** [verdaccio/monorepo#417]
**Describe the bug**
`node-fetch` is at `v2.6.0` and should be updated to `v2.6.1` 

https://github.com/verdaccio/monorepo/blob/01a4142dd1ee6bd2b45aef3f323b3181784336bb/plugins/audit/package.json#L34
https://github.com/advisories/GHSA-w7rc-rwvf-8q5r

**To Reproduce**

**Expected behavior**

**Screenshots**

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: [e.g. verdaccio:beta]
 - Docker commands [e.g. docker pull ...]
 - Docker Version [e.g. v18.05.0-ce-rc1]

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 

**Debugging output**
 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
 - `$ npm -ddd` prints:
 - `$ npm config get registry` prints:

**Additional context**

**Comment by juanpicado** [comment]
Thanks @viceice for the advice , I'll patch it today. I should have a bot 😊 enabled, or had it ... need to double check why is not enabled.

**Comment by viceice** [comment]
At lease you should enable dependabot notifications.  Also [renovate](https://github.com/renovatebot/renovate) is a pretty good bot 😉

**Comment by juanpicado** [comment]
https://github.com/verdaccio/monorepo/pull/420
