### ISSUE TITLE
Local caching of vulnerabilities 

### ISSUE THREAD

**Issue by bufferoverflow** [verdaccio/monorepo#44]
Node security wg is planning to create a dedicated repo for the known vulnerabilities, see 
https://github.com/nodejs/security-wg/issues/359#issuecomment-410079404

Using that sources instead of redirecting to upstream npm could be a nice option for verdaccio-audit.

**Comment by wzrdtales** [comment]
Just got blocked by npm completely on a CI b/c of the stupid audit API of them... . Having this use the current db and downloading it, or at least caching the result for some time is something that needs to be added. Will see if I can put some time into this...
