### ISSUE TITLE
clean up eslint warnings

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/monorepo#46]
Currently we don't comply with the current `eslint` rules we are encouraging for all organization projects. We need to clean this up.

```
✖ 198 problems (0 errors, 198 warnings)
  0 errors and 3 warnings potentially fixable with the `--fix` option.
````

plugin: **google-cloud**

**Comment by sergiohgz** [comment]
This issue apply for several packages in the monorepo. We have to unify some settings and rules in the main eslint-config pacakge.

Also, if we run `eslint --print-config index.js | eslint-config-prettier-check` in `tools/eslint-config`, we will get some conflicting rules we need to resolve in the unification, as all projects has that settings set

**Comment by sergiohgz** [comment]
I can do this for the packages that have been imported and take care of future packages

**Comment by sergiohgz** [comment]
I am with the refactor in progress. I have removed some unnecessary `.eslintrc` files which settings do not apply anymore. There are some rules we cannot avoid (like `@typescript-eslint/no-explicit-any`), but it is better to have the warning to remember we have to fix them in a future.

**Comment by ryhinchey** [comment]
I just started working through a bunch of eslint warnings.  I also get a bunch of warnings when running the `5.x` branch of Verdaccio Core.  Should a separate issue be created for lint warnings in Verdaccio Core or are those less important for 5.x?

**Comment by juanpicado** [comment]
hi @ryhinchey ! glad to see your request. My strategy would  be, in this order:

1. Fix `eslint` warnings for `verdaccio/master`
2. Wait until I rebase `5.x` on top of `master`
3. Fix `eslint` warnings on `verdaccio/5.x`

I must rebase `5.x` quite often and `master` will be under development most likely the whole 2020. 

I think we have also warnings on this repo, @sergiohgz could you confirm whether we can use `master` since you recently moved to `10.x-next`?

**Comment by ryhinchey** [comment]
thanks @juanpicado !

**Comment by dnafication** [comment]
About 75 of the warnings are due to `max-len` which is simple to get rid of.

```
warning  This line has a length of 103. Maximum allowed is 100  max-len
```

where should the PR go? `master` or `5.x`

**Comment by juanpicado** [comment]
@dnafication  yes, please,  same settings as `5.x`, this code eventually would be part of `5.x`.

**Comment by juanpicado** [comment]
Closing this, moved tothe core repo .
