### ISSUE TITLE
Feature to fetch all npm packages 

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/monorepo#58]
#### My reason:
I want to retrieve all packages from storage.

Refers to: https://github.com/verdaccio/verdaccio/issues/706

**Comment by cjsfj** [comment]
Are you looking for a UI? You can request a json object of the cached packages by visiting http://<your_verdaccio>/-/all

**Comment by juanpicado** [comment]
There are two things to keep on mind here.

- UI is not ready for such amount of packages
- Performance optimizations are need it, that endpoint actually stream from the remote.

The root of the request is rather only display what is in the cache.

**Comment by juanpicado** [comment]
duplicated
