### ISSUE TITLE
fs.exists is deprecated

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/monorepo#60]
#### My reason:

We use `fs.exists` at least twice in our source code, this has been deprecated, we should upgrade it.

https://nodejs.org/api/fs.html#fs_fs_exists_path_callback

**Comment by Shriram-Balaji** [comment]
@juanpicado I'd like to take a dig at this issue.

**Comment by juanpicado** [comment]
It's booked then :-)

**Comment by Shriram-Balaji** [comment]
@juanpicado The `memory-fs` library we are using doesn't seem to have a `fs.access` method. Although it has `fs.stat`, node [docs](https://nodejs.org/api/fs.html#fs_fs_stat_path_options_callback) don't seem recommend it:

> Using fs.stat() to check for the existence of a file before calling fs.open(), fs.readFile() or fs.writeFile() is not recommended. Instead, user code should open/read/write the file directly and handle the error raised if the file is not available.
> 
> To check if a file exists without manipulating it afterwards, fs.access() is recommended.

Also, the `memory-fs` library itself hasn't been updated in a while, so the chances of an upstream change seem to be minimal. 

Do you have a suggestion on what should be done?

**Comment by juanpicado** [comment]
Here you can find some inspiration https://github.com/verdaccio/local-storage/pull/174

![Screen Shot 2019-10-01 at 7 49 09 AM](https://user-images.githubusercontent.com/558752/65937387-04ac5500-e420-11e9-910f-ea79cc13f883.png)

**Comment by Shriram-Balaji** [comment]
@juanpicado Thanks for the pointers. I have a PR up for review :)

**Comment by DanielRuf** [comment]
existsSync is not deprecated afaik.

https://nodejs.org/api/fs.html#fs_fs_existssync_path

**Comment by DanielRuf** [comment]
Also it was deprecated since NodeJS 1.0.0
<img width="730" alt="Bildschirmfoto 2019-10-05 um 11 38 13" src="https://user-images.githubusercontent.com/827205/66253191-a6a3a880-e764-11e9-90db-48a47e167b10.png">

**Comment by DanielRuf** [comment]
> fs.exists() is deprecated, but fs.existsSync() is not. The callback parameter to fs.exists() accepts parameters that are inconsistent with other Node.js callbacks. fs.existsSync() does not use a callback.

**Comment by DanielRuf** [comment]
See https://nodejs.org/docs/latest-v4.x/api/fs.html#fs_fs_exists_path_callback ;-)

**Comment by juanpicado** [comment]
FYI https://github.com/verdaccio/monorepo/pull/159

**Comment by DanielRuf** [comment]
I already saw it and gave feedback there ;-)

<img width="746" alt="Bildschirmfoto 2019-10-05 um 11 59 47" src="https://user-images.githubusercontent.com/827205/66253380-abb62700-e767-11e9-829e-18e332fa174d.png">
