### ISSUE TITLE
Syntax highlighting in readme

### ISSUE THREAD

**Issue by cesco69** [verdaccio/monorepo#633]
**Is your feature request related to a problem? Please describe.**
I want syntax highlighting in readme eg.:
```ts
function sayHello() {
   alert('Hello!');
}
```

instead of :

```
function sayHello() {
   alert('Hello!');
}
```

**Describe the solution you'd like**
verdaccio use marked https://github.com/verdaccio/monorepo/blob/9.x/core/readme/src/index.ts#L15 for parsing the markdown code, and marked has syntax highlighting options https://marked.js.org/using_advanced#highlight

**Comment by juanpicado** [comment]
Would you like to PR? I'll be happy to review it.

**Comment by cesco69** [comment]
Hi @juanpicado , sorry, I'cant, but it seem really simple to implement, eg.:

```ts
import createDOMPurify from 'dompurify';
import { JSDOM } from 'jsdom';

const DOMPurify = createDOMPurify(new JSDOM('').window);
const { marked } = require('marked');

// set syntax highlighting option
marked.setOptions({
  highlight: function(code, lang, callback) {
    // retrive the language from first line, eg.:
    // ```ts
    // const demo = 'My typescript code';
    // ```
    // supported language see https://pygments.org/languages/ 
    const format = code ? code.split('\n')[0] : null;
    if( format ){
      require('pygmentize-bundled') ({ lang: lang, format: format  }, code, function (err, result) {
         callback(err, result.toString());
      });
    } else {
       callback(null, code);
    }
  }
});

export default function parseReadme(
  readme: string,
  options: { pathname?: string | void } = {}
): string | void {
  let result;

  if (readme) {
    result = DOMPurify.sanitize(
      marked(readme, {
        sanitize: false,
      }).trim()
    );

    if ('string' === typeof options.pathname) {
      result = result.replace(/href="#/gi, `href="${options.pathname}#`);
    }
  }

  return result;
}
```

**Comment by juanpicado** [comment]
@cesco69 https://www.npmjs.com/package/pygmentize-bundled is 8 years old and deprecated, do you know another alternative ?

**Comment by juanpicado** [comment]
:) ok I think got it 
<img width="1251" alt="Screenshot 2022-11-19 at 11 45 50" src="https://user-images.githubusercontent.com/558752/202846870-340af3ec-688f-4efb-8750-f485f29bb7a0.png">

**Comment by juanpicado** [comment]
closed by https://github.com/verdaccio/verdaccio/pull/3505
