### ISSUE TITLE
Improve @verdaccio/eslint-config

### ISSUE THREAD

**Issue by sergiohgz** [verdaccio/monorepo#8]
Improve our Eslint config after adding some projects to this monorepo, as it is difficult to create a common settings if we don't use it.

**Comment by juanpicado** [comment]
We can implement it on 2 projects. lock-file, streams.

**Comment by juanpicado** [comment]
If all goes well, next httpassw and local-storage. Last step, verdaccio itself. Wdth?

**Comment by juanpicado** [comment]
@sergiohgz how we publish to npm this?

**Comment by sergiohgz** [comment]
@juanpicado I'm going to create the roadmap of the project in order to advance this weekend.

I think we should create a basic babel-preset (this is more difficult as I have to review changes in Babel 7) and publish a pre-release of them (v4.0.0-alpha.0?).
If the first 2 projects you mention are stable and we won't develop too much in them for the meanwhile, we can start using the new packages and, if we believe they are working correctly and development cycle is correct, we should import them here.

About how we publish to NPM, this project structure is prepared to have a CI lifecycle similar to Verdaccio main project, we will run version script defined in main `package.json` locally to create the version tag and, when pushed, CI will perform the script publish that we have defined below version.
Before running the first publish I need to review CircleCI config file because I want to add some steps and see if the line where we execute publish has the `--yes` flag to not break build.

**Comment by juanpicado** [comment]
> I think we should create a basic babel-preset (this is more difficult as I have to review changes in Babel 7) and publish a pre-release of them (v4.0.0-alpha.0?). if the first 2 projects you mention are stable and we won't develop too much in them for the meanwhile, we can start using the new packages and, if we believe they are working correctly and development cycle is correct, we should import them here.

I'll vote to move Babel 7 and then try to use it on the 2 first projects. Those have an easier Babel setup.

> About how we publish to NPM, this project structure is prepared to have a CI lifecycle similar to Verdaccio main project, we will run version script defined in main package.json locally to create the version tag and, when pushed, CI will perform the script publish that we have defined below version.
Before running the first publish I need to review CircleCI config file because I want to add some steps and see if the line where we execute publish has the --yes flag to not break build.

:) This would be a good chance to test Verdaccio as E2E tool in our own packages. What do you think?

**Comment by sergiohgz** [comment]
We have no need to improve right now as the old package was removed and substituted with a new one that is really great and used in all the projects, so we close this :smiley:
