### ISSUE TITLE
Use babel-preset and eslint-config in some example projects

### ISSUE THREAD

**Issue by sergiohgz** [verdaccio/monorepo#9]
After first publish of **@verdaccio/babel-preset** and **@verdaccio/eslint-config** we should use in two projects to look how we should improve them and test how we feel with monorepo.

The pacakges proposed are the described in #8 by @juanpicado:
- [ ] lock-file
- [ ] streams

After that, we can follow with
- [ ] htpasswd
- [ ] local-storage

**Comment by juanpicado** [comment]
btw, keep on mind we might use Typescript in some packages if we create this preset with Babel 7.

**Comment by sergiohgz** [comment]
Both projects are used when they were developed outside the monorepo, so we do not need to keep this open
